<?php
/* @var $form \Zend\Form\Form */

$title = 'Edit blog post';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute(
	'action', $this->url('zfcadmin/maglblog/post', array(
		'action' => 'edit',
		'id' => $this->id,
		)
));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formRow($form->get('csrf'));

/* @var $blogPostFieldset \MaglBlog\Form\BlogPostFieldset */
$blogPostFieldset = $form->get('blog_post');

foreach ($blogPostFieldset as $element) {
	?>
	<div class="form-group">
		<?= $element->getLabel() ? $this->formLabel($element) : '' ?>
		<?= $this->formElement($element); ?>
		<?= $this->formElementErrors($element); ?>
	</div>
	<?php
}
echo $this->formElement($form->get('submit'));
echo $this->form()->closeTag();
